name: aoi_remote
description: "Media controls"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^0.13.3
  rename_app: ^1.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_vibrate: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/img/

# run this to generate icons
#   flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/img/app_icon.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "lib/assets/img/app_icon.png"
  windows:
    generate: true
    image_path: "lib/assets/img/app_icon.png"
  macos:
    generate: true
    image_path: "lib/assets/img/app_icon.png"
